-- KIIZU database foundation
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique not null, avatar_url text, coins bigint not null default 0 check (coins >= 0), wins integer not null default 0, losses integer not null default 0, games_played integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.games (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text, min_players integer not null default 2, max_players integer not null default 2, unlocked_by_default boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.items (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, category text not null, price bigint not null default 0 check(price >= 0), unique_item boolean not null default true, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.inventory (user_id uuid references public.profiles(id) on delete cascade, item_id uuid references public.items(id) on delete cascade, purchased_at timestamptz not null default now(), primary key(user_id,item_id));
create table if not exists public.game_unlocks (user_id uuid references public.profiles(id) on delete cascade, game_id uuid references public.games(id) on delete cascade, unlocked_at timestamptz not null default now(), primary key(user_id,game_id));
create table if not exists public.equipped_items (user_id uuid references public.profiles(id) on delete cascade, item_id uuid references public.items(id) on delete cascade, slot text not null, equipped_at timestamptz not null default now(), primary key(user_id,slot));
create table if not exists public.matches (id uuid primary key default gen_random_uuid(), game_id uuid references public.games(id), host_id uuid references public.profiles(id), code text unique, status text not null default 'waiting' check(status in ('waiting','starting','playing','finished')), created_at timestamptz not null default now(), started_at timestamptz, finished_at timestamptz);
create table if not exists public.match_players (match_id uuid references public.matches(id) on delete cascade, user_id uuid references public.profiles(id) on delete cascade, score integer not null default 0, placement integer, joined_at timestamptz not null default now(), primary key(match_id,user_id));
create table if not exists public.friendships (requester_id uuid references public.profiles(id) on delete cascade, addressee_id uuid references public.profiles(id) on delete cascade, status text not null default 'pending' check(status in ('pending','accepted','rejected')), created_at timestamptz not null default now(), primary key(requester_id,addressee_id), check(requester_id <> addressee_id));
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete cascade, type text not null, payload jsonb not null default '{}', read_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.coin_transactions (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete cascade, amount bigint not null, reason text not null, match_id uuid references public.matches(id), created_at timestamptz not null default now());
create index if not exists idx_matches_status on public.matches(status);
create index if not exists idx_match_players_user on public.match_players(user_id);
create index if not exists idx_notifications_user on public.notifications(user_id,created_at desc);
alter table public.profiles enable row level security;
alter table public.inventory enable row level security;
alter table public.game_unlocks enable row level security;
alter table public.equipped_items enable row level security;
alter table public.matches enable row level security;
alter table public.match_players enable row level security;
alter table public.friendships enable row level security;
alter table public.notifications enable row level security;
alter table public.coin_transactions enable row level security;
create policy "profiles readable" on public.profiles for select using (true);
create policy "own profile update" on public.profiles for update using (auth.uid()=id) with check (auth.uid()=id);
create policy "own inventory read" on public.inventory for select using (auth.uid()=user_id);
create policy "own unlocks read" on public.game_unlocks for select using (auth.uid()=user_id);
create policy "own equipped read" on public.equipped_items for select using (auth.uid()=user_id);
create policy "match participants read" on public.match_players for select using (exists(select 1 from public.match_players mp where mp.match_id=match_players.match_id and mp.user_id=auth.uid()));
create policy "matches participants read" on public.matches for select using (exists(select 1 from public.match_players mp where mp.match_id=matches.id and mp.user_id=auth.uid()));
create policy "own transactions read" on public.coin_transactions for select using (auth.uid()=user_id);
