import { requireAuth, signOut } from "./auth.js";
import { getProfile } from "./profile.js";
import { supabase } from "./app.js";
import { toast } from "./ui.js";
import { initMotion } from "./animations.js";
let heartbeatTimer=null;
async function updatePresence(status="online"){try{await supabase.rpc("set_presence",{p_status:status})}catch{}}
async function startPresence(){await updatePresence("online");clearInterval(heartbeatTimer);heartbeatTimer=setInterval(()=>updatePresence("online"),30000);window.addEventListener("pagehide",()=>updatePresence("offline"),{once:true})}
export async function getPublicStats(){const[{count:total},{count:online}]=await Promise.all([supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("profiles").select("id",{count:"exact",head:true}).eq("status","online").gt("last_seen",new Date(Date.now()-90000).toISOString())]);return{total:total??0,online:online??0}}
function safe(v){return String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function avatar(url,name){return url?'<img class="account-avatar" src="'+safe(url)+'" alt="">':'<span class="account-avatar">'+safe((name||"K").slice(0,1).toUpperCase())+"</span>"}
function setupAccount(profile){const host=document.querySelector(".user-pill");if(!host)return;const name=profile.username||"Usuario";host.innerHTML='<button class="account-trigger" type="button" aria-expanded="false">'+avatar(profile.avatar_url,name)+'<span class="account-name">'+safe(name)+'</span><span>⌄</span></button><div class="account-menu"><div class="account-menu-head">'+avatar(profile.avatar_url,name)+'<div><strong>'+safe(name)+'</strong><small>🪙 '+Number(profile.coins??0).toLocaleString()+" Coins</small></div></div><a href="profile.html">Perfil</a><a href="inventory.html">Inventario</a><a href="friends.html">Amigos</a><button class="danger" data-signout type="button">Cerrar sesión</button></div>";const trigger=host.querySelector(".account-trigger");trigger.onclick=e=>{e.stopPropagation();const open=host.classList.toggle("is-open");trigger.setAttribute("aria-expanded",String(open))};host.querySelector("[data-signout]").onclick=async()=>{await updatePresence("offline");try{await signOut()}catch{toast("No se pudo cerrar sesión.","error")}};document.addEventListener("click",()=>{host.classList.remove("is-open");trigger.setAttribute("aria-expanded","false")})}
export async function bootShell(){const session=await requireAuth();if(!session)return null;const profile=await getProfile(session.user.id);document.querySelectorAll("[data-username]").forEach(el=>el.textContent=profile.username);document.querySelectorAll("[data-coins]").forEach(el=>el.textContent=Number(profile.coins).toLocaleString());setupAccount(profile);await startPresence();initMotion();return{session,profile}}
